// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class renamed_Ingredients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamed_Ingredients));
        
        string IMigrationMetadata.Id
        {
            get { return "202008212021433_renamed_Ingredients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
