// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update_MenuRecipe_Added_Primary_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_MenuRecipe_Added_Primary_key));
        
        string IMigrationMetadata.Id
        {
            get { return "202009072030590_Update_MenuRecipe_Added_Primary_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
