// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_primary_key_to_recipeIngredients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_primary_key_to_recipeIngredients));
        
        string IMigrationMetadata.Id
        {
            get { return "202009081721470_Add_primary_key_to_recipeIngredients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
