// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class image_column_in_recipeTable_renamed_to_RecipeImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_column_in_recipeTable_renamed_to_RecipeImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021854176_image_column_in_recipeTable_renamed_to_RecipeImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
