// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_DbSet_Recipes_and_DbSet_Ingridients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_DbSet_Recipes_and_DbSet_Ingridients));
        
        string IMigrationMetadata.Id
        {
            get { return "202008161722116_Add_DbSet_Recipes_and_DbSet_Ingridients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
