// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update_DayId_as_Key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_DayId_as_Key));
        
        string IMigrationMetadata.Id
        {
            get { return "202009071515284_Update_DayId_as_Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
