// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Many_to_many_relationShip_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Many_to_many_relationShip_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241750545_Many_to_many_relationShip_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
