// <auto-generated />
namespace MenuMaker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_imagePath_to_Recipe_remove_ImageByteArray : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_imagePath_to_Recipe_remove_ImageByteArray));
        
        string IMigrationMetadata.Id
        {
            get { return "202009032001531_add_imagePath_to_Recipe_remove_ImageByteArray"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
